"""TD系テンプレ(TDTD用)の図。tools/import_td_templates.py で生成(手で編集しない)。

【2026-09-30・利用者の要望】袋がずれたまま組み直すTDTDに向けて、テトリス堂のTD系テンプレを収録する。
記号は opener_data.py と同じ。出典はそれぞれのURL(テトリス堂)。
"""

TD_EXTRA_SOURCE_FORMS = (
    (
        'ホットケーキ積み',
        'Pancake Stacking',
        'https://shiwehi.com/tetris/template/pancake.php',
        (
            ('1巡目とミノ順', "\n".join(('----------', '--------i-', '-ss-----i-', 'ssl----tij', 'ool-zzttij', 'ooll-zztjj'))),
            ('1巡目とミノ順', "\n".join(('----------', '-i--------', '-i-----zz-', 'lit----jzz', 'littss-joo', 'lltss-jjoo'))),
            ('2巡目・3巡目 > 基本形', "\n".join(('----------', '--------li', 'jjss--llli', 'jss---ooci', 'jcc-zzooci', 'ccc--zzccc', 'ccc-cccccc', 'cccc-ccccc'))),
            ('2巡目・3巡目 > 基本形', "\n".join(('----------', '--------cc', 'cccc--cccc', 'ccc---cccc', 'CCCUCCCCCC', 'CCCUUCCCCC', 'CCCUCCCCCC', 'cccc-ccccc'))),
            ('2巡目・3巡目 > 基本形', "\n".join(('----------', 'oojiiiilll', 'oojjjsslcc', 'ccccsscccc', 'ccctttcccc', 'cccctccccc'))),
            ('2巡目・3巡目 > 基本形', "\n".join(('----------', 'oollljiiii', 'oolzzjjjcc', 'cccczzcccc', 'ccctttcccc', 'cccctccccc'))),
            ('2巡目・3巡目 > 基本形', "\n".join(('----------', 'jiiiioolll', 'jjjzzoolcc', 'cccczzcccc', 'ccctttcccc', 'cccctccccc'))),
            ('2巡目・3巡目 > 妥協系', "\n".join(('--------oo', 'i-------oo', 'i-ss---jll', 'iss----jcl', 'icc-zzjjcl', 'ccc--zzccc', 'ccc-cccccc', 'cccc-ccccc'))),
            ('2巡目・3巡目 > 妥協系', "\n".join(('--------cc', 'c-------cc', 'c-cc---ccc', 'ccc----ccc', 'CCCUCCCCCC', 'CCCUUCCCCC', 'CCCUCCCCCC', 'cccc-ccccc'))),
            ('2巡目・3巡目 > 妥協系', "\n".join(('----------', 'lliiiioocc', 'cljjjsoocc', 'clccjssccc', 'ccctttsccc', 'cccctccccc'))),
            ('2巡目・3巡目 > ハイド形', "\n".join(('oo--------', 'oo-------i', 'jjss--l--i', 'jss---l-ci', 'jcc-zzllci', 'ccc--zzccc', 'ccc-cccccc', 'cccc-ccccc'))),
            ('2巡目・3巡目 > ハイド形', "\n".join(('cc--------', 'cc-------c', 'cccc--c--c', 'ccc---c-cc', 'CCCUCCCCCC', 'CCCUUCCCCC', 'CCCUCCCCCC', 'cccc-ccccc'))),
            ('2巡目・3巡目 > ハイド形', "\n".join(('----------', 'cclllooijj', 'cclzzooijc', 'cccczzcijc', 'ccctttcicc', 'cccctccccc'))),
            ('2巡目・3巡目 > ハイド形', "\n".join(('----------', 'ccoolllijj', 'ccoolssijc', 'ccccsscijc', 'ccctttcicc', 'cccctccccc'))),
            ('2巡目・3巡目 > ハイド形', "\n".join(('----------', 'ccjiiiilll', 'ccjjjsslzc', 'ccccssczzc', 'ccctttczcc', 'cccctccccc'))),
            ('2巡目・3巡目 > ハイド形', "\n".join(('----------', 'ccoojjiiii', 'ccoojlllzc', 'ccccjlczzc', 'ccctttczcc', 'cccctccccc'))),
            ('2巡目・3巡目 > ハイド形', "\n".join(('----------', 'ccooljiiii', 'ccooljjjzc', 'ccccllczzc', 'ccctttczcc', 'cccctccccc'))),
        ),
    ),
    (
        'くろみつ砲',
        'Kuromitsu Cannon',
        'https://shiwehi.com/tetris/template/kuromitsu.php',
        (
            ('1巡目とミノ順', "\n".join(('----------', '----------', '-oo-----zi', '-oojt--zzi', '-ssjtt-zli', 'ssjjt-llli'))),
            ('1巡目とミノ順', "\n".join(('----------', '----------', '-zz-----ss', '-jzzt--ssl', '-joott-lll', 'jjoot-iiii'))),
            ('2巡目→3巡目 > 理想形(%Z>%Oの場合)', "\n".join(('----------', '------ooll', '--ss--oozl', 'issj---zzl', 'iccjjjUzcc', 'iccccUUccc', 'icccccUccc', 'ccccc-cccc'))),
            ('2巡目→3巡目 > 理想形(%Z>%Oの場合)', "\n".join(('----------', 'llljjjiiii', 'lsszzjcccc', 'sscczzcccc', 'cccctttccc', 'ccccctcccc'))),
            ('2巡目→3巡目 > 理想形(%Z>%Oの場合)', "\n".join(('----------', 'loojjjiiii', 'loozzjcccc', 'llcczzcccc', 'cccctttccc', 'ccccctcccc'))),
            ('2巡目→3巡目 > 理想形(%Z>%Oの場合)', "\n".join(('----------', 'jjjslliiii', 'oojsslcccc', 'ooccslcccc', 'cccctttccc', 'ccccctcccc'))),
            ('2巡目→3巡目 > 理想形(%Z>%Oの場合)', "\n".join(('----------', 'jjzslliiii', 'jzzsslcccc', 'jzccslcccc', 'cccctttccc', 'ccccctcccc'))),
            ('2巡目→3巡目 > 理想形(%Z>%Oの場合)', "\n".join(('----------', 'jjzllliiii', 'jzzloocccc', 'jzccoocccc', 'cccctttccc', 'ccccctcccc'))),
            ('2巡目→3巡目 > 理想形(%Z>%Oの場合)', "\n".join(('----------', 'llloojiiii', 'lssoojcccc', 'ssccjjcccc', 'cccctttccc', 'ccccctcccc'))),
            ('2巡目→3巡目 > 通常形(%O>%S>%Zの場合)', "\n".join(('--z-------', '-zz-------', '-zss--lloo', 'issj---loo', 'iccjjjUlcc', 'iccccUUccc', 'icccccUccc', 'ccccc-cccc'))),
            ('2巡目→3巡目 > 通常形(%O>%S>%Zの場合)', "\n".join(('----------', 'jjcooiiiil', 'jccoosslll', 'jcccsscccc', 'cccctttccc', 'ccccctcccc'))),
            ('2巡目→3巡目 > 通常形(%O>%S>%Zの場合)', "\n".join(('----------', 'jjcsiiiioo', 'jccssllloo', 'jcccslcccc', 'cccctttccc', 'ccccctcccc'))),
            ('2巡目→3巡目 > 通常形(%O>%S>%Zの場合)', "\n".join(('----------', 'jjciiiiloo', 'jcczzllloo', 'jccczzcccc', 'cccctttccc', 'ccccctcccc'))),
            ('2巡目→3巡目 > 妥協形1(%O>%Z>%I>%Sの場合)', "\n".join(('----------', 's--z------', 'sszz--lloo', 'iszj---loo', 'iccjjjUlcc', 'iccccUUccc', 'icccccUccc', 'ccccc-cccc'))),
            ('2巡目→3巡目 > 妥協形1(%O>%Z>%I>%Sの場合)', "\n".join(('----------', 'zzjjjiiiil', 'czzcjsslll', 'ccccsscccc', 'cccctttccc', 'ccccctcccc'))),
            ('2巡目→3巡目 > 妥協形2(%O>%Z>%S>%Iの場合)', "\n".join(('-------zz-', '--------zz', '--ss--lloo', 'issj---loo', 'iccjjjUlcc', 'iccccUUccc', 'icccccUccc', 'ccccc-cccc'))),
            ('2巡目→3巡目 > 妥協形2(%O>%Z>%S>%Iの場合)', "\n".join(('----------', '-------ssi', '------ssli', '------llli', 'jjj--zzcci', 'ooj---zzcc', 'oocc--cccc', 'ccccUUUccc', 'cccccUcccc'))),
            ('2巡目→3巡目 > 妥協形2(%O>%Z>%S>%Iの場合)', "\n".join(('----------', '-------ooi', '------jooi', '------jjji', 'lll--zzcci', 'lss---zzcc', 'sscc--cccc', 'ccccUUUccc', 'cccccUcccc'))),
            ('2巡目→3巡目 > 妥協形2(%O>%Z>%S>%Iの場合)', "\n".join(('--------ll', '-------ool', 'i------ool', 'ijjz---ccc', 'ijzz--cccc', 'ijzUUUcccc', 'cccsUccccc', 'cccss-cccc', 'ccccs-cccc'))),
            ('2巡目→3巡目 > 妥協形2(%O>%Z>%S>%Iの場合)', "\n".join(('--------zj', '-------zzj', 'i------zjj', 'iloo---ccc', 'iloo--cccc', 'illUUUcccc', 'cccsUccccc', 'cccss-cccc', 'ccccs-cccc'))),
            ('2巡目→3巡目 > 妥協形2(%O>%Z>%S>%Iの場合)', "\n".join(('----------', 'siiiitttcc', 'ssoozztccc', 'csoojzzccc', 'ccccjjjccc', 'ccccllcccc', 'ccccclcccc', 'ccccclcccc'))),
            ('2巡目→3巡目 > 妥協形2(%O>%Z>%S>%Iの場合)', "\n".join(('----------', 'jjjootttcc', 'zzjoostccc', 'czzllssccc', 'cccclisccc', 'cccclicccc', 'cccccicccc', 'cccccicccc'))),
        ),
    ),
    (
        'PC-Spin',
        'PC-Spin (Okey Version)',
        'https://shiwehi.com/tetris/template/pcspin_ok.php',
        (
            ('1巡目とミノ順', "\n".join(('----------', '-i--------', '-i--------', '-i--------', 'si--------', 'ss----too-', 'js-zzttool', 'jjj-zztlll'))),
            ('1巡目とミノ順', "\n".join(('----------', '--------i-', '--------i-', '--------i-', '--------iz', '-oot----zz', 'joottss-zl', 'jjjtss-lll'))),
            ('2,3巡目 > %J>%Oの場合(理想形)', "\n".join(('ill-------', 'icl-------', 'icl-----oo', 'ic----ssoo', 'ccUzzssjjj', 'ccUUzzcccj', 'ccUccccccc', 'ccc-cccccc'))),
            ('2,3巡目 > %J>%Oの場合(理想形)', "\n".join(('----------', 'cccjjjiiii', 'cccoojzlll', 'cccoozzlcc', 'cctttzcccc', 'ccctcccccc'))),
            ('2,3巡目 > %J>%Oの場合(理想形)', "\n".join(('----------', 'cccooiiiil', 'cccoozzlll', 'cccjjjzzcc', 'cctttjcccc', 'ccctcccccc'))),
            ('2,3巡目 > %J>%Oの場合(理想形)', "\n".join(('----------', 'cccoosiiii', 'cccoosslll', 'cccjjjslcc', 'cctttjcccc', 'ccctcccccc'))),
            ('2,3巡目 > %J>%Oの場合(理想形)', "\n".join(('----------', 'cccjjiiiil', 'cccjszzlll', 'cccjsszzcc', 'cctttscccc', 'ccctcccccc'))),
            ('2,3巡目 > %O>%Jの場合(標準形)', "\n".join(('ill-------', 'icl-------', 'icl--jj---', 'ic---joos-', 'ccUzzjooss', 'ccUUzzcccs', 'ccUccccccc', 'ccc-cccccc'))),
            ('2,3巡目 > %O>%Jの場合(標準形)', "\n".join(('----------', 'cccjjjiiii', 'cccoojzzll', 'cccoocczzl', 'cctttccccl', 'ccctcccccc'))),
            ('2,3巡目 > %O>%Jの場合(標準形)', "\n".join(('----------', 'cccjjzllli', 'cccjzzlooi', 'cccjzccooi', 'cctttcccci', 'ccctcccccc'))),
            ('2,3巡目 > %O>%Jの場合(標準形)', "\n".join(('----------', 'ccclllooji', 'ccclssooji', 'cccssccjji', 'cctttcccci', 'ccctcccccc'))),
            ('2,3巡目 > %O>%Jの場合(標準形)', "\n".join(('----------', 'cccjjjslli', 'cccoojssli', 'cccooccsli', 'cctttcccci', 'ccctcccccc'))),
            ('2,3巡目 > %O>%Jの場合(標準形)', "\n".join(('----------', 'cccllljjji', 'ccclsszzji', 'cccsscczzi', 'cctttcccci', 'ccctcccccc'))),
        ),
    ),
    (
        '皐月積み',
        'Satsuki Stacking',
        'https://shiwehi.com/tetris/template/satsuki.php',
        (
            ('1巡目とミノ順', "\n".join(('----------', 's---------', 'ss--------', 'is--------', 'il----t---', 'il-zzttoo-', 'ill-zztoo-'))),
            ('1巡目とミノ順', "\n".join(('----------', '---------z', '--------zz', '--------zi', '---t----ji', '-oottss-ji', '-ootss-jji'))),
            ('理想形 > 2巡目：S>JLの場合', "\n".join(('----------', 'ooJ-------', 'ooJ-------', 'cJJ--jj---', 'cc---jsll-', 'cc-zzjssli', 'cc--zzcsli', 'cc-cccccci', 'ccc-ccccci'))),
            ('理想形 > 2巡目：JorL>Sの場合', "\n".join(('----------', 'ooj-------', 'ooj-------', 'cjj--ls---', 'cc---lssJ-', 'cc-zzllsJi', 'cc--zzcJJi', 'cc-cccccci', 'ccc-ccccci'))),
            ('理想形 > 2巡目：JorL>Sの場合', "\n".join(('----------', 'sll-------', 'ssl-------', 'csl--jj---', 'cc---jooJ-', 'cc-zzjooJi', 'cc--zzcJJi', 'cc-cccccci', 'ccc-ccccci'))),
            ('理想形 > 2巡目：JorL>Sの場合', "\n".join(('----------', 'ccc-------', 'ccc-------', 'ccc--cc---', 'cc---cccc-', 'ccUccccccc', 'ccUUcccccc', 'ccUccccccc', 'ccc-cccccc'))),
            ('理想形 > 3巡目', "\n".join(('----------', 'cccjjjiiii', 'cccoojzzll', 'cccoocczzl', 'cctttccccl', 'ccctcccccc'))),
            ('理想形 > 3巡目', "\n".join(('----------', 'cccjjzllli', 'cccjzzlooi', 'cccjzccooi', 'cctttcccci', 'ccctcccccc'))),
            ('理想形 > 3巡目', "\n".join(('----------', 'ccclllooji', 'ccclssooji', 'cccssccjji', 'cctttcccci', 'ccctcccccc'))),
            ('理想形 > 3巡目', "\n".join(('----------', 'cccjjjslli', 'cccoojssli', 'cccooccsli', 'cctttcccci', 'ccctcccccc'))),
            ('理想形 > 3巡目', "\n".join(('----------', 'cccllljjji', 'ccclsszzji', 'cccsscczzi', 'cctttcccci', 'ccctcccccc'))),
            ('理想形 > 3巡目', "\n".join(('----------', 'cccjjzslli', 'cccjzzssli', 'cccjzccsli', 'cctttcccci', 'ccctcccccc'))),
            ('理想形 > 3巡目', "\n".join(('----------', '-z-ss-----', 'zzss------', 'zjjj------', 'cccj--llli', 'ccc---looi', 'ccct-ccooi', 'cctt-cccci', 'ccctcccccc'))),
            ('理想形 > 3巡目', "\n".join(('----------', '----------', '----------', '-----oos--', 'ccc--oossi', 'ccc---zzsi', 'ccct-cczzi', 'cctt-cccci', 'ccctcccccc'))),
            ('理想形 > 3巡目', "\n".join(('----------', '----------', '----------', '-----szz--', 'ccc--sszzi', 'ccc---sooi', 'ccct-ccooi', 'cctt-cccci', 'ccctcccccc'))),
            ('妥協形 > 2巡目', "\n".join(('----------', 'lll-------', 'loo--s----', 'coo--ss---', 'cc---js-J-', 'cc-zzjjjJi', 'cc--zzcJJi', 'cc-cccccci', 'ccc-ccccci'))),
            ('妥協形 > 2巡目', "\n".join(('----------', 'ccc-------', 'ccc--c----', 'ccc--cc---', 'cc---cc-c-', 'ccUccccccc', 'ccUUcccccc', 'ccUccccccc', 'ccc-cccccc'))),
            ('妥協形 > 3巡目', "\n".join(('----------', 'ccciiiijjj', 'cccoocllsj', 'cccoocclss', 'cctttcclcs', 'ccctcccccc'))),
        ),
    ),
    (
        'ベーカリーTD',
        'Bakery TD (Riif Stacking v5)',
        'https://shiwehi.com/tetris/template/bakery.php',
        (
            ('1巡目とミノ順', "\n".join(('----------', '----------', '----------', '------i---', 'l----tijj-', 'l-zzttijoo', 'll-zztijoo'))),
            ('1巡目とミノ順', "\n".join(('----------', '----------', '----------', '---i------', '-llit----j', 'oolittss-j', 'oolitss-jj'))),
            ('1巡目とミノ順', "\n".join(('----------', '----------', '--------s-', '------i-ss', 'l----tijjs', 'l-zzttijoo', 'll-zztijoo'))),
            ('O>S 2巡目～3巡目 > 2巡目', "\n".join(('----------', '-----ss---', 'jj--ssSlli', 'j---ooSSli', 'jUzzoocSli', 'cUUzzcccci', 'cUcccccccc', 'cc-ccccccc'))),
            ('O>S 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'oojjziiiil', 'oojzzcclll', 'ccjzcccccc', 'ctttcccccc', 'cctccccccc'))),
            ('S>O 2巡目～3巡目 > 2巡目', "\n".join(('---------i', '-------ooi', 'jj--l-sooi', 'j---l-ssSi', 'jUzzllcsSS', 'cUUzzccccS', 'cUcccccccc', 'cc-ccccccc'))),
            ('S>O 2巡目～3巡目 > 3巡目', "\n".join(('----------', 'lllooiiiic', 'lzzoojjccc', 'cczzcjcccc', 'ctttcjcccc', 'cctccccccc'))),
            ('S>O 2巡目～3巡目 > 3巡目', "\n".join(('----------', 'oojjzilllc', 'oojzzilccc', 'ccjzcicccc', 'ctttcicccc', 'cctccccccc'))),
            ('S>O 2巡目～3巡目 > 3巡目', "\n".join(('----------', 'oollliiiic', 'oolssjjccc', 'ccsscjcccc', 'ctttcjcccc', 'cctccccccc'))),
        ),
    ),
    (
        'タンドリーチキン積み',
        'Tandoori Chicken Stacking (Riif Stacking v3)',
        'https://shiwehi.com/tetris/template/tandoori.php',
        (
            ('1巡目とミノ順', "\n".join(('----------', 's---------', 'ss--------', 'is--------', 'il----t---', 'il-zztt-oo', 'ill-zzt-oo'))),
            ('1巡目とミノ順', "\n".join(('----------', '---------z', '--------zz', '--------zi', '---t----ji', 'oo-ttss-ji', 'oo-tss-jji'))),
            ('1巡目とミノ順', "\n".join(('----------', 's---------', 'ss--------', 'is--------', 'il----tjj-', 'il-zzttjoo', 'ill-zztjoo'))),
            ('S>I 2巡目～3巡目 > 2巡目', "\n".join(('ooj------i', 'ooj------i', 'cjj------i', 'cc-----lsi', 'ccUzzlllss', 'ccUUzzcJJs', 'ccUccccJcc', 'ccc-cccJcc'))),
            ('S>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccjjzzllc', 'cccjoozzlc', 'cccjoosslc', 'cctttssccc', 'ccctcccccc'))),
            ('S>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccjjssllc', 'cccjssoolc', 'cccjzzoolc', 'cctttzzccc', 'ccctcccccc'))),
            ('S>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccllljjjc', 'ccclsszzjc', 'cccssoozzc', 'cctttooccc', 'ccctcccccc'))),
            ('S>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccjjiiiic', 'cccjsllooc', 'cccjsslooc', 'cctttslccc', 'ccctcccccc'))),
            ('S>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccooiiiic', 'cccooljjjc', 'ccclllssjc', 'cctttssccc', 'ccctcccccc'))),
            ('S>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'ccciiiillc', 'cccoojjzlc', 'cccoojzzlc', 'cctttjzccc', 'ccctcccccc'))),
            ('S>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'ccciiiiooc', 'cccllljooc', 'ccclzzjjjc', 'cctttzzccc', 'ccctcccccc'))),
            ('S>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'ccciiiizjc', 'cccoolzzjc', 'cccoolzjjc', 'cctttllccc', 'ccctcccccc'))),
            ('S>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'ccciiiiooc', 'cccllljooc', 'ccclzzjjjc', 'cctttzzccc', 'ccctcccccc'))),
            ('S>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccjjoollc', 'cccjsoozlc', 'cccjsszzlc', 'cctttszccc', 'ccctcccccc'))),
            ('S>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccooiiiic', 'cccoozjjjc', 'ccctzzssjc', 'ccttzssccc', 'ccctcccccc'))),
            ('I>S 2巡目～3巡目 > 2巡目', "\n".join(('lll-------', 'loo-------', 'coo-----jj', 'cc----ssjJ', 'ccUzzssijJ', 'ccUUzzciJJ', 'ccUccccicc', 'ccc-cccicc'))),
            ('I>S 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccjjjiiii', 'cccoojzlll', 'cccoozzlcc', 'cctttzcccc', 'ccctcccccc'))),
            ('I>S 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccooiiiil', 'cccoozzlll', 'cccjjjzzcc', 'cctttjcccc', 'ccctcccccc'))),
            ('I>S 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccoosiiii', 'cccoosslll', 'cccjjjslcc', 'cctttjcccc', 'ccctcccccc'))),
            ('I>S 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccjjiiiil', 'cccjszzlll', 'cccjsszzcc', 'cctttscccc', 'ccctcccccc'))),
            ('J>I 2巡目～3巡目 > 2巡目', "\n".join(('lll------i', 'loo------i', 'coo------i', 'cc----ss-i', 'ccUzzssjjj', 'ccUUzzcccj', 'ccUccccccc', 'ccc-cccccc'))),
            ('J>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccjjjllic', 'cccoojzlic', 'cccoozzlic', 'cctttzccic', 'ccctcccccc'))),
            ('J>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccjjzooic', 'cccjzzooic', 'cccjzlllic', 'cctttlccic', 'ccctcccccc'))),
            ('J>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccooiiiic', 'cccoozzllc', 'cccjjjzzlc', 'cctttjcclc', 'ccctcccccc'))),
            ('J>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccoosllic', 'cccoosslic', 'cccjjjslic', 'cctttjccic', 'ccctcccccc'))),
            ('J>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccjjlllic', 'cccjslooic', 'cccjssooic', 'cctttsccic', 'ccctcccccc'))),
            ('J>I 2巡目～3巡目 > 2巡目', "\n".join(('----------', 'cccjjiiiic', 'cccjszzllc', 'cccjsszzlc', 'cctttscclc', 'ccctcccccc'))),
        ),
    ),
)
